@startuml
package Model {
left to right direction

+class OrdemServico {
    -int id
    -double valorOrcamento
    -String descricao 
    -Material materialUtilizado
    -Cliente cliente
    -Hardware hardware
    -Tecnico tecnicoResponsável
    
    +OrdemServico(Cliente cliente, Hardware hardware)
    +void verOS(OrdemServico os)
}

+interface State {
    
}
rectangle Atores{
    +abstract Pessoa {
        -int id
        -String nome
        -String cpf
        -int Idade
        -String endereco
    }

    +class Tecnico {
        +void fazerOrcamento(double valor)
        +void atualizarOrcamento(double valor)
        +void assumirOS(OrdemServico os)
        +void finalizarOS(OrdemServico os)
        +void executarOS(OrdemServico os, Material materialUtilizado)
    }
    
    +class Administrador {
        +void excluirOS(Ordemservico os, Administrador admnistrador)
        +void abrirOS(Administrador administrador, Cliente cliente, Hardware hardware)
        +void atualizarOS(Cliente cliente, Hardware hardware)
    }
    
    +class Atendente {
        +void reqExclusão(Atendente atendente, String motivo)
        +void abrirOS(Atendente atendente, Cliente cliente, Hardware hardware)
        +void atualizarOS(Cliente cliente, Hardware hardware)
    }
    
    +class Cliente {
        -Hardware hardware
    }
}
rectangle Produto {
    +class Hardware {
        -Cliente cliente
        -Tipo tipo
        -String numeroSerie
        -String descricaoProblema
    }
    
    +class Material {
        +ArrayList<Peça> removerEstoque()
    }
    
    +class Peca {
        -int id
        -String nome
        -TipoPeca tipoPeca
        +criarPeca()
    }
    
    +enum TipoPeca{
        COMPUTADOR
        NOTEBOOK
        CELULAR
        OUTROS
    }
    



+class Estoque {
    +void verPecas()
    +void adicionarPecas(Peca peca, int quantidade)
    +void removerPecas(Peca peca, int quantidade)
    +atualizarEstoque()
}
}

+interface Relatorio {
    +verRelatorioFinanceiro()
    +verRelatorioEstoque()
    +verRelatorioOS()
    +verRelatorioAtendente()
    +verRelatorioTecnico()
    +verClientes()
}


    Peca  --|> TipoPeca
    
    Estoque --> Peca
    
    Cliente --|> Pessoa
    Cliente --> OrdemServico
    
    Administrador --|> Pessoa
    Administrador ..|> Relatorio
    
    Tecnico --|> Pessoa
    Tecnico --> OrdemServico
    
    Atendente --|> Pessoa
    Atendente --> OrdemServico

    Material ..> OrdemServico
    Material --> Peca
    
    Hardware --> OrdemServico 
    
    OrdemServico ..|> State
}
@enduml
